### ISSUE TITLE
DFD Comments Oct 2

### ISSUE THREAD

**Issue by germonprez** [cvong1001/3420ISQAAssignment1#17]
Hi Calvin, 

Here are a few comments: 

Please remove your first DFD image. I had made comments on it before I realized there was a better one below. 

1) Software Package License Results (going into the DB) --should be--> Software Package License and Vulnerability Results. Include all information in this dataflow. 

2) All Software Package License Results --Should be--> Software Package License and Vulnerability Results. 

3) You don't need the dataflows between these two processes. 

<img width="143" alt="screen shot 2016-10-02 at 5 57 34 pm" src="https://cloud.githubusercontent.com/assets/656208/19024461/c24281f8-88c9-11e6-8c7c-d7163ba7bdaf.png">

4) These processes and the similar for the Manager... First, I think that you have the arrow directionality mixed up for the Developer. Second, I think that a better dataflow (in both cases) would be Request Software Project Policy (to the DB) and Software Project Policy (from the DB).

I think that your structure is really good and I appreciate your consistent work here. Well done, I think that these changes are pretty easy to take care of. 

MG

**Comment by cvong1001** [comment]
Updated DFD based on your comments.
