### ISSUE TITLE
DFD Comments

### ISSUE THREAD

**Issue by germonprez** [cvong1001/3420ISQAAssignment1#8]
Hi Calvin, 

here are a few comments: 

1) Remove the squirrel image 
2) Identify OSS Components should be Identified OSS Components (use the noun version as this represents the actual data being passed). 
3) The database is not following the DFD drawing conventions from the slides. 
4) Typically External Entities (Developer) will communicate with processes. It is rare that a database will communicate with an external entity. 

I hope these are helpful!

Matt

**Comment by cvong1001** [comment]
1) Removed the squirrel image
2) Changed Identify to Identified
3) Hoping it follows DFD drawing convention
4) External Entities are communicating with processes.
