### ISSUE TITLE
DFD Comments 9/22

### ISSUE THREAD

**Issue by germonprez** [cvong1001/3420ISQAAssignment1#9]
Hi Calvin, 

A few comments. 

1) You don't have a datastore. You are going to need one to store the results of the license scan. This is the item that has two lines (see the slides). You have the Database there but right now it is represented as an Entity. 

2) You have to be 100% consistent in your naming. For example: 

Send Identified Software Packages --should be--> Software Package License Results 
Identified Software Licenses --should be--> Software Package License Results

These are the same things so they should have the same name. 

3) I don't think that you need Send Identified Software Packages leaving the database. You can return the Software Package License Results to the Developer directly from the Manage Software Package for License Scanning process. 

4) The Manage should connect to a new process called something like: Query DB for All Software Package and License Information. This process would then connect directly to the Database. 

This is certainly improving. Thanks for the ongoing work.

**Comment by cvong1001** [comment]
1) Updated database to two lines to indicate it is a database.
2) Renamed the data flows to "Software Package License Results".
3) Did not send data flow back to Manage Software Package for License Scanning process. Instead sent data flow to new process "Query DB for All Software Package and License Information".
4. Manager is receiving data flow from new process "Query DB for All Software Package and License Information".
